"""Pydantic v2 API DTOs mirroring spec/api_contract_v1.md (camelCase wire format).

One module per contract section. Import from ``arena.schemas``.
"""

from __future__ import annotations

from arena.schemas.admin import (
    AdminDlqItem,
    AdminFlag,
    AdminIntegrityItem,
    AdminMetric,
    AdminOverview,
    AdminQueue,
    AdminRiotApi,
    AdminSeason,
    AdminWorker,
)
from arena.schemas.champions import (
    BuildEntry,
    BuildTeammate,
    ChampionAugments,
    ChampionBuildResponse,
    ChampionMainsResponse,
    ChampionSynergy,
    ChampionSynergyGroup,
    ChampionSynergyGroupResponse,
    ChampionSynergyResponse,
    ChampionTrendPoint,
    ChampionTrendResponse,
    ChampRow,
    ChampTier,
    ChampTierlistResponse,
    ChampTopPlayer,
    SynergyChampion,
    SynergyTier,
    SynergyTierlistResponse,
    TopBuildResponse,
)
from arena.schemas.common import (
    ArenaModel,
    AvatarColors,
    Format,
    Modifier,
    PlayerTag,
    Severity,
    TierKey,
    arena_camel,
)
from arena.schemas.leaderboard import LeaderboardChampion, LeaderboardResponse, LeaderboardRow
from arena.schemas.match import (
    MatchDetail,
    MatchIntegrityFlag,
    MatchPlayer,
    SubTeam,
)
from arena.schemas.meta import (
    ActivityDay,
    ActivityResponse,
    LastUpdate,
    LastUpdateGlobal,
    LastUpdateTier,
    RecordsResponse,
    SeasonRecord,
)
from arena.schemas.player import (
    ChampFacet,
    ChampStat,
    CrHistoryPoint,
    FormDot,
    H2HPlayerRef,
    H2HRow,
    MatchesSummary,
    PlayerMatch,
    PlayerMatchesResponse,
    PlayerMatchRich,
    PlayerProfile,
    SeasonArchive,
)
from arena.schemas.tournaments import (
    AccessRequest,
    AccessResponse,
    AccessTeamSlot,
    ConductEntry,
    CreateTeamRequest,
    CreateTeamResponse,
    JoinTeamRequest,
    JoinTeamResponse,
    PlayerSlot,
    PlayerSlotEmpty,
    PlayerSlotFilled,
    PrizeRow,
    PrizeSplitEntry,
    ResultPenalty,
    ScoringEntry,
    SetMatchLinkRequest,
    StandingRow,
    SubmitResultRequest,
    TeamRoster,
    TournamentCreate,
    TournamentDetail,
    TournamentEntry,
    TournamentListItem,
    TournamentMatch,
    TournamentMatchResult,
    TournamentMatchResultEntry,
    TournamentMatchResultRow,
    TournamentRules,
)

__all__ = [
    # common
    "ArenaModel",
    "AvatarColors",
    "Format",
    "Modifier",
    "PlayerTag",
    "Severity",
    "TierKey",
    "arena_camel",
    # leaderboard
    "LeaderboardChampion",
    "LeaderboardResponse",
    "LeaderboardRow",
    # player
    "ChampStat",
    "CrHistoryPoint",
    "FormDot",
    "H2HPlayerRef",
    "H2HRow",
    "ChampFacet",
    "MatchesSummary",
    "PlayerMatch",
    "PlayerMatchRich",
    "PlayerMatchesResponse",
    "PlayerProfile",
    "SeasonArchive",
    # match
    "MatchDetail",
    "MatchIntegrityFlag",
    "MatchPlayer",
    "SubTeam",
    # champions
    "ChampRow",
    "ChampTier",
    "ChampTierlistResponse",
    "ChampTopPlayer",
    "ChampionSynergy",
    "ChampionSynergyResponse",
    "ChampionSynergyGroup",
    "ChampionSynergyGroupResponse",
    "SynergyTier",
    "SynergyTierlistResponse",
    "ChampionTrendPoint",
    "ChampionTrendResponse",
    "ChampionMainsResponse",
    "SynergyChampion",
    "BuildEntry",
    "BuildTeammate",
    "ChampionAugments",
    "ChampionBuildResponse",
    "TopBuildResponse",
    # tournaments
    "AccessRequest",
    "AccessResponse",
    "AccessTeamSlot",
    "ConductEntry",
    "CreateTeamRequest",
    "CreateTeamResponse",
    "JoinTeamRequest",
    "JoinTeamResponse",
    "PlayerSlot",
    "PlayerSlotEmpty",
    "PlayerSlotFilled",
    "PrizeRow",
    "PrizeSplitEntry",
    "ResultPenalty",
    "ScoringEntry",
    "SetMatchLinkRequest",
    "StandingRow",
    "SubmitResultRequest",
    "TeamRoster",
    "TournamentCreate",
    "TournamentDetail",
    "TournamentEntry",
    "TournamentListItem",
    "TournamentMatch",
    "TournamentMatchResult",
    "TournamentMatchResultEntry",
    "TournamentMatchResultRow",
    "TournamentRules",
    # admin
    "AdminDlqItem",
    "AdminFlag",
    "AdminIntegrityItem",
    "AdminMetric",
    "AdminOverview",
    "AdminQueue",
    "AdminRiotApi",
    "AdminSeason",
    "AdminWorker",
    # meta
    "LastUpdate",
    "LastUpdateGlobal",
    "LastUpdateTier",
    "ActivityDay",
    "ActivityResponse",
    "SeasonRecord",
    "RecordsResponse",
]
